language: php

php: [5.3, 5.4, 5.5, hhvm]

branches:
  except:
    - /^bugfix\/.*$/
    - /^feature\/.*$/
    - /^optimization\/.*$/

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install --dev --prefer-source
  - export PATH=./vendor/bin:$PATH

script:
  - behat -fprogress
